import type { NextPage } from "next";
import Head from "next/head";
// import { useAuth } from "@clerk/nextjs";
import Link from "next/link";

// import NavigationBar from "../components/NavBar";

// const PostCard: React.FC<{
//   post: inferProcedureOutput<AppRouter["post"]["all"]>[number];
// }> = ({ post }) => {
//   return (
//     <div className="max-w-2xl rounded-lg border-2 border-gray-500 p-4 transition-all hover:scale-[101%]">
//       <h2 className="text-2xl font-bold text-[hsl(280,100%,70%)]">
//         {post.title}
//       </h2>
//       <p>{post.content}</p>
//     </div>
//   );
// };

const Home: NextPage = () => {
  // const postQuery = trpc.post.all.useQuery();
  // const { isSignedIn } = useAuth();

  return (
    <>
      <Head>
        <title>Greenthumb</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-center bg-gradient-to-b from-white to-slate-200">
        {/* {isSignedIn && <SignedInPage />} */}
        {/* {!isSignedIn && ( */}
          <div className="container flex flex-col items-center justify-center gap-12 px-4 py-8">
            <h1 className="text-5xl font-extrabold tracking-tight sm:text-[5rem]">
              <span className="text-green-600 ">greenthumb</span>
            </h1>
            <div className="flex flex-row items-center justify-center gap-4">
              <p className="rounded-xl bg-green-600 px-4 py-2 text-center text-2xl font-bold text-white">
                <Link href="/sign-in">Sign In</Link>
              </p>
            </div>

            {/* <div className="flex h-[60vh] justify-center overflow-y-scroll px-4 text-2xl">
            {postQuery.data ? (
              <div className="flex flex-col gap-4">
                {postQuery.data?.map((p) => {
                  return <PostCard key={p.id} post={p} />;
                })}
              </div>
            ) : (
              <p>Loading..</p>
            )}
          </div> */}
          </div>
        {/* )} */}
      </main>
    </>
  );
};

export default Home;

const SignedInPage: NextPage = () => {
  return (
    <>
      {/* <NavigationBar /> */}
    </>
  );
};
